name = "eglise-app"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]
account_id = "c6408608867f869f85cc16572418424a"
main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "eglise-db"
database_id = "38d955d1-b300-445e-b06e-cfd9b1b953f0"

[triggers]
crons = ["0 8 * * *"]

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1
