-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS SOMMES UN', '', NULL, '' FROM songs WHERE title = 'NOUS SOMMES UN' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS T''''ADORONS (NOUS T’AIMONS)', '', NULL, '' FROM songs WHERE title = 'NOUS T''ADORONS (NOUS T’AIMONS)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS T''''ADORONS (O PERE)', '', NULL, '' FROM songs WHERE title = 'NOUS T''ADORONS (O PERE)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS TIENDRONS', '', NULL, '' FROM songs WHERE title = 'NOUS TIENDRONS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, ' NOUS TOUS QUI REFLETONS', '', NULL, '' FROM songs WHERE title = 'NOUS TOUS QUI REFLETONS' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en D', '', NULL, 'Couplet 1 [D]Nous venons dans Ta présence Pour [Em]chanter Tes lou[A]anges Et [Em]notre recon[A]naissance De ce que [G]Tu as [D]ac[Em]com[D]pli Couplet 2 [G]Tu [D]nous as donné Ta vie Ton [Em]amour et Ta [A]joie Et [Em]la louange enva[A]hit nos cœurs [G]Passion[D]nés [Em]de [D]Toi Refrain 1 [A]Tu es [Bm]le créateur puissant L''a[F#m]gneau ressuscité Toi seul [G]a pu triompher De la [D]mort du péché Refrain 2 [A]Tu as [Bm]délivré Ton peuple Pour [F#m]la vraie liberté Je veux sui[G]vre Tes pas Chaque [A]jour être avec [A]Toi ' FROM songs WHERE title = 'NOUS VENONS DANS TA PRESENCE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS VOULONS VOIR JESUS ELEVE', '', NULL, 'G D Em C G Nous voulons voir Jésus élevé. Comme un étendard sur ce pays D Em C G Pour montrer à tous la vérité, Et le chemin vers le ciel D Em C G Nous voulons voir, nous voulons voir, Nous voulons voir Jésus élevé (bis) D Em D Em Pas à pas allons de l''avant, Peu à peu gagnons du terrain. D Em C D La prière est notre puissance, Les murailles s''écroulent à terre, A terre, à terre, à terre.' FROM songs WHERE title = 'NOUS VOULONS VOIR JESUS ELEVE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OCEAN', '', NULL, '[Bm] [A] [D] [A] [G] Couplet 1: [Bm]Oui, Tu m’appelles par-[A]delà des [D]eaux Dans l’inconn[A]ue, aucun app[G]ui [Bm]Et Tu te révèles [A]dans ce [D]mystère. Dans l''a[A]bîme, ma foi de[G]meure, Refrain;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'O DIEU TU ES GRAND', '', NULL, '' FROM songs WHERE title = 'O DIEU TU ES GRAND' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OFFRONS AU SEIGNEUR RECONNAISSANCE', '', NULL, '' FROM songs WHERE title = 'OFFRONS AU SEIGNEUR RECONNAISSANCE' LIMIT 1;