-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'QUE TA GLOIRE DESCENDE (EN CE LIEU)', '', NULL, '' FROM songs WHERE title = 'QUE TA GLOIRE DESCENDE (EN CE LIEU)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'QUE TON REGNE VIENNE (SEIGNEUR, TU APPELLES)', '', NULL, '' FROM songs WHERE title = 'QUE TON REGNE VIENNE (SEIGNEUR, TU APPELLES)' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en Am', '', NULL, '[A]Qui est sem[F]blable au lion A l''a[C]gneau, assis sur le [G]trône Les monts s''in[F]clinent, l''océan ru[C]git devant le Sei[G]gneur [F]Louez Ado[Am]naï, du [G]lever du soleil Et jus[Dm]qu''à la fin du jour [F]Louez Ado[Am]naï, Toutes [G]les nations du monde Tous les [Dm]anges Et tous les saints te [Bb]louent' FROM songs WHERE title = 'QUI EST SEMBLABLE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'QU’IL EN SOIT AINSI', '', NULL, '' FROM songs WHERE title = 'QU’IL EN SOIT AINSI' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'REGNE EN MOI (Dans le monde entier)', '', NULL, '' FROM songs WHERE title = 'REGNE EN MOI (Dans le monde entier)' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'RENDONS GRACE', '', NULL, 'Refrain: [Em]Rendons grâce à Dieu car Il [D]est [Em]bon Car son [C]amour [D]demeure à [Em]jamais [Em]Rendons grâce, [D]louons le Sei[Em]gneur Pour sa [C]sainte[D]té et sa [Em]splendeur Couplet: Et si [Am]l''ennemi vient nous [Em]cerner Et [Am]veut nous [D]enva[G]hir [Em] C''est le [Am]Dieu puissant qui com[Em]battra Et la [F#]victoire est dans ses [B]mains [F#] [B] [B7]' FROM songs WHERE title = 'RENDONS GRACE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'REVEILLE MON ESPRIT', '', NULL, '' FROM songs WHERE title = 'REVEILLE MON ESPRIT' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'REVETONS L''''ARMURE', '', NULL, 'Re[Em]vêtons l’armure et ga[D/E]gnons le pa[Em]ys, La [Em]victoire est [D]à notre [CM7]Dieu.[D] Toute [Em]arme forgée contre [D/E]nous est bri[Em]sée, La [Em]victoire est [D/E]à notre [Em]Dieu. Oui, chan[D]tons [G]gloi[D]re, [C]hon[D][G]neur, [G]Force et lou[D]ange au Sei[Em]gneur. [C]Chan[D]tons [G]gloi[D]re, [C]hon[D][G]neur, [G]Force et lou[B]ange au Seign[Em]eur.[D/E][D/E][Em] Lors[Em]que les ténèbres se[D/E]raient comme un [Em]fleuve, La [Em]victoire est [D]à notre [CM7]Dieu.[D] Il [Em]déploie sur nous le pou[D/E]voir de son [Em]sang, La [Em]victoire est [D/E]à notre [Em]Dieu. Quand [Em]l’ennemi vient près de [D/E]toi, ne crains [Em]rien, La [Em]victoire est [D]à notre [CM7]Dieu.[D] Tu [Em]peux résister car tu [D/E]es rache[Em]té, La [Em]victoire est [D/E]à notre [Em]Dieu. [Em]Force et lou[D/E]ange, [Em]force et lou[D/E]ange, [Em]Force et lou[D/E]ange au Sei[Em]gneur.' FROM songs WHERE title = 'REVETONS L''ARMURE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'SAINT, SAINT, SAINT (est l''''Eternel des armées) Gm', '', NULL, 'Refrain [Cm]Saint, Saint, [Dm]Saint, est l’E[Gm]ternel des armées Toute la [Eb]terre est rem[F]plie de sa [Gm]gloire Couplet 1 L’Eternel se [Eb]tient sur un [F]trône éle[Bb]vé [F] [Gm] Son manteau de [Cm7]gloire rem[Dm]plit sa mai[Gm]son Des séra[Eb]phins ne [F]cessent de cri[Bb]er [F] Couplet 2 Et les fonda[Eb]tions tremblent au [F]son de cette [Bb]voix [F] [Gm] Toute la mai[Cm]son se rem[Dm]plit de fu[Gm]mée Je tombe à ge[Eb]noux, je [F]ne peux que cri[Bb]er [Gm] Couplet 3 L''éternel me [Eb]dit qui [F]pourrait j''envo[Bb]yer [F] [Gm] Qui se lève[Cm]ra et [Dm]marchera pour [Gm]nous [Cm] [Gm] Je dis: “ me voi[Eb]ci ” par[F]tout je chante[Bb]rai' FROM songs WHERE title = 'SAINT, SAINT, SAINT (est l''Eternel des armées)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'SAINT, SAINT, SAINT (HOSANNA)', '', NULL, '' FROM songs WHERE title = 'SAINT, SAINT, SAINT (HOSANNA)' LIMIT 1;