-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'TU ES SAINT (KADOSH)', '', NULL, '' FROM songs WHERE title = 'TU ES SAINT (KADOSH)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'TU ES SEIGNEUR', '', NULL, '' FROM songs WHERE title = 'TU ES SEIGNEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'TU M''''AS CHOISI', '', NULL, '' FROM songs WHERE title = 'TU M''AS CHOISI' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'TU TRACES UN CHEMIN', '', NULL, 'Couplet 1 Tu es [C]là, présent parmi [G]nous, Je T''a[D]dore, je T''a[Em]dore Tu es [C]là, agissant parmi [G]nous, Je T''a[D]dore, je T''a[Em]dore Refrain [C] Tu traces un chemin, opère des miracles [G] Tu tiens Tes promesses, Lumière dans les té[D]nèbres Mon Dieu, c''est ce que Tu [Em]es Couplet 2 Tu es [C]là, transformant nos [G]vies, Je T''adore, je T''a[Em]dore Tu es [C]là, guérissant nos [G]coeurs, Je T''adore, je T''a[Em]dore Tu es [C]là, transformant nos [G]vies, Je T''adore, je T''a[Em]dore Tu es [C]là, restaures les coeurs b[G]risés, Je T''adore, je T''a[Em]dore Pont [C] Et quand je ne le vois pas Tu es là [G] Et quand je ne le sens pas Tu es là [D] Tu agiras, Tu agiras encore, [Em]Tu agiras , Tu agiras encore' FROM songs WHERE title = 'TU TRACES UN CHEMIN' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'UNE CHOSE', '', NULL, '' FROM songs WHERE title = 'UNE CHOSE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'UN JOUR DANS TES PARVIS', '', NULL, '' FROM songs WHERE title = 'UN JOUR DANS TES PARVIS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'UN SI GRAND MIRACLE', '', NULL, '' FROM songs WHERE title = 'UN SI GRAND MIRACLE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'UN VIN NOUVEAU', '', NULL, '' FROM songs WHERE title = 'UN VIN NOUVEAU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VASES D''''ARGILE (Grâce Infinie)', '', NULL, '' FROM songs WHERE title = 'VASES D''ARGILE (Grâce Infinie)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VENEZ LE CELEBRER', '', NULL, '' FROM songs WHERE title = 'VENEZ LE CELEBRER' LIMIT 1;