-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'AMOUR EXTRAVAGANT', '', NULL, '' FROM songs WHERE title = 'AMOUR EXTRAVAGANT' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ABBA PERE', '', NULL, '' FROM songs WHERE title = 'ABBA PERE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en G', '', NULL, ' Intro C2 Em7 G/D D C2 Em7 G/D D Couplet G D/F# Em C A/C# D Abrite-moi sous tes ailes, G/B C Am D Couvre-moi par ta main puissante. Refrain G G/B C D G Même si les océans se déchaînent, G G/B C D Em Je les traverserai avec Toi. Em C D Em Père, Tu domines les tempêtes, G/B C D C2 Je suis tranquille car Tu es là. Couplet G D/F# Em C A/C# D En Jésus seul je me confie, G/B C Am D Il me donne force, calme et puissance.' FROM songs WHERE title = 'ABRITE-MOI' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ACCUEILLI DANS LES PARVIS DU ROI', '', NULL, '' FROM songs WHERE title = 'ACCUEILLI DANS LES PARVIS DU ROI' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'test', '', NULL, '[Dm]Accueilli dans les parvis du Roi, Je suis introduit dans ta présence Je suis là sur le lieu de ta grâce, Pourtant je m''avance avec révérence Qui au ciel est comparable à toi ? Et qui sur la terre est ton égal ? Tu es élevé bien au dessus de tout, Je veux m''incliner pour t''exalter Et je tombe face à terre en présence de ta gloire Oui je tombe face à terre en présence de ta gloire Viens rayonner de ta gloire, Viens rayonner de ta gloire Prends la place qui te revient, ô Roi de gloire [Dm]' FROM songs WHERE title = 'ACCUEILLI DANS LES PARVIS DU ROI' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en D', '', NULL, 'Couplet 1 Quel sau[D]veur merveilleux je po[C#/A]]ssède Il s''est [G]sacrifié pour [D]moi Et sa [D]vie innocente, il [A]cède Pour mo[Bm]urir sur l''infâme [G/D]bois Couplet 2 Il re[D]nonce à la gloire cé[F#m]]les[A]te Pour le [Em]plan rédemp[G]teur de [D]Dieu L''appa[D]rence est la plus mo[A]deste Ô quel [Bm]prix pour me [D]rendre heu[G]reux Refrain Atta[D]ché à la [Bm]croix pour [Asus4]moi Atta[Em]ché à la [A]croix pour [Bm]moi Il a [D]pris mon péché Il m''a [G]délivré Atta[D]ché à la croix [A]pour [D] [Bm]moi G D G Couplet 3 Maltrai[D]té, innocent, pour ma [A]vie Pour mes [G]iniquités, [D]brisé Et char[D]gé de mes mala[A]dies Il mou[G]rut pour guérir, sau[A]ver A Em G Bm A Em G A Refrain Atta[E]ché à la [C#m]croix pour [Bsus4]moi Atta[F#m7]ché à la [Bsus4]croix pour [C#m]moi Il a [E]pris mon péché Il m''a [A]délivré Atta[E]ché à la [croix [B]pour [C#m]]moi ou [E]' FROM songs WHERE title = 'ATTACHE A LA CROIX' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'AU CŒUR DE LA LOUANGE', '', NULL, 'D A Em7 A Le chant terminé, le rideau retombe, Je viens simplement D A Em7 A Porter mon offrande, car j''ai le désir De réjouir ton cœur Em7 A Em7 A J''apporte plus qu''un beau chant, chanter ne suffit pas Pour répondre à ton appel Em7 A Em7 A Les apparences sont trompeuses, tu vois bien au delà, O Dieu, tu sondes mon cœur D A Em7 G A D Je reviens au cœur de la louange, Tout est centré sur toi, centré sur toi Jésus. D A Em7 G A D Oui je renonce à tous mes faux semblants, Pour tout centrer sur toi, centrer sur toi Jésus. D A Em7 A Roi d''éternité, qui peut exprimer Ce dont tu es digne? D A Em7 A Bien que faible et pauvre, je te donne tout, Prends toute ma vie. ' FROM songs WHERE title = 'AU CŒUR DE LA LOUANGE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'A CELUI QUI NOUS AIME', '', NULL, '' FROM songs WHERE title = 'A CELUI QUI NOUS AIME' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'A GENOUX', '', NULL, '' FROM songs WHERE title = 'A GENOUX' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en F', '', NULL, 'couplet 1 [Dm]Elevé à la [C]droite de Dieu [Gm]Couronné de [Dm]mille cou[C]ronnes [F]Tu resplendis comme un [C]soleil radieux [Gm]Les êtres crient au[Asus4]tour de ton [A]trône Refrain [Dm]A l''agneau de Dieu soit la [Gm]gloire [Gm]A l''agneau de Dieu, la vic[C]toire [F]A l''agneau de Dieu soit le [C]règne Pour tous les [Gm]siècles, A[Asus4]men Couplet 2 [Dm]L''esprit Saint et [C]l''épouse fidèle [Gm]Disent: viens c''est leur [Dm]coeur qui a[C]ppelle [F]Viens, ô Jésus, toi [C]l''époux bien-aimé [Gm]Tous tes élus ne [Asus4]cessent de chan[A]ter Couplet 3 [Dm]Tous les peuples et [C]toutes les nations [Gm]D''un seul coeur, avec [Dm]les milliers [C]d''anges [F]Entonneront en l''hon[C]neur de son nom [Gm]Ce chant de gloire avec [Asus4]force et lou[A]ange' FROM songs WHERE title = 'A L''AGNEAU DE DIEU' LIMIT 1;