-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NI PAR PUISSANCE', '', NULL, '' FROM songs WHERE title = 'NI PAR PUISSANCE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOTRE DIEU', '', NULL, '' FROM songs WHERE title = 'NOTRE DIEU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOTRE PERE', '', NULL, '' FROM songs WHERE title = 'NOTRE PERE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOTRE PERE QUI ES AUX CIEUX', '', NULL, '' FROM songs WHERE title = 'NOTRE PERE QUI ES AUX CIEUX' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS ADORONS ADONAÏ', '', NULL, ' {key:Em} [Em]Nous adorons Adonaï,[Am] [D]Nous ado[D/F#]rons Él-Shad[G]daï.[Bsus4][B7] [Em]Nous élevons ton grand nom,[Am] [Em]Nous te lou[B7]ons Sei[Em]gneur. [E] D’un même [Am]cœur pour le Sei[D]gneur, Le créa[G]teur du [D/F#]vrai bonheur.[Em] [Am]Tu es [B7]glorieux, mon [Em]roi. [E] Tu fais de [Am]moi ton servi[D]teur. Père, je veux [G]que ma [D/F#]joie de[Em]meure, Car c’est en [C]toi que je veux [B7]être éternelle[Em]ment.' FROM songs WHERE title = 'NOUS ADORONS ADONAÏ' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS AVONS SOIF DE PLUS', '', NULL, ' Em D G C Em7 D C 1 - Nous avons soif de plus, Souffle de Dieu, nous t''attendons Em D G C Em7 D C Nous avons soif de plus, Esprit de Dieu, souffle sur nous Am G D Remplis nous à nouveau (bis) G D Em7 C Feu dévorant, attise en nous, La passion pour ton nom G D Esprit de Dieu, tombe en ce lieu, Em7 D C Sois le seul maître, Sois le seul maître en nous Em D G C Em7 D C 2 - Viens comme un vent violent, Nous revêtir de ta puissance Em D G C Em7 D C Délivre les captifs Libère-nous pour te louer Am G D Seigneur, envoie ta gloire (bis)' FROM songs WHERE title = 'NOUS AVONS SOIF DE PLUS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS CONTEMPLONS', '', NULL, '' FROM songs WHERE title = 'NOUS CONTEMPLONS' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS CRIONS VICTOIRE', '', NULL, '[Em]Nous voulons [C]être [D]cette généra[Em]tion, Remplie du Saint-Es[C]prit [D]et de compa[Em]ssion [C]Nous voulons [D]vivre à fond notre pas[Em]sion, [C]Sans compromis ni [D]doute en Christ Nous nous con[Em]fions [G]Nous por[C]tons [D]la croix du sa[Em]lut [G]Le me[C]ssage que [D]Satan est vain[Em]cu Nous crions [C]Victoire, [D]Honneur, Lou[Bm]ange à notre [Em]Dieu (bis) [Em]Nous décla[C]rons qu’il [D]n’y a qu’une i[Em]ssue, Oui c’est Jésus-[C]Christ [D]le chemin du sa[Em]lut [C]Nous décla[D]rons qu’il n’y a qu’un seul [Em]Dieu, En[C]voyé sur la [D]terre Jésus venu des [Em]cieux [G]Nous sommes [C]prêts à [D]lui donner nos [Em]vies, [G]Nous vou[C]lons sa [D]gloire sur ce [Em]pays ' FROM songs WHERE title = 'NOUS CRIONS VICTOIRE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS CROYONS', '', NULL, '' FROM songs WHERE title = 'NOUS CROYONS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'NOUS NE SOMMES PLUS', '', NULL, '' FROM songs WHERE title = 'NOUS NE SOMMES PLUS' LIMIT 1;