-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OH HAPPY DAY', '', NULL, '' FROM songs WHERE title = 'OH HAPPY DAY' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OH JESUS, MON SAUVEUR', '', NULL, '' FROM songs WHERE title = 'OH JESUS, MON SAUVEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OH ! VIENS DEVANT LE SAINT TRONE', '', NULL, '' FROM songs WHERE title = 'OH ! VIENS DEVANT LE SAINT TRONE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'O SAINT ESPRIT, (Viens des quatre vents)', '', NULL, '' FROM songs WHERE title = 'O SAINT ESPRIT, (Viens des quatre vents)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OUI, DIEU REGNE', '', NULL, '' FROM songs WHERE title = 'OUI, DIEU REGNE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OUVRE LES YEUX', '', NULL, '' FROM songs WHERE title = 'OUVRE LES YEUX' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'OUVRE LES YEUX DE MON CŒUR', '', NULL, 'Refrain [C]Ouvre les yeux de mon coeur [G]Ouvre les yeux de mon coeur Je désire [Am7]Te voir[F] Je désire [C]Te voir Couplet Elevé [Gsus4]au plus haut des [Am7]cieux, [F]Rayonnant de l’éclat de [G]Ta gloire Répands Ton amour, Ta [Am7]force Alors que [Dm]nous chantons: “Tu es [Gsus4]saint” Refrain [C]Ouvre les yeux de mon coeur [G]Ouvre les yeux de mon coeur Je désire [Am7]Te voir[F] Je désire [Abmaj7]]Te voir [Gsus4] [C]Ouvre les yeux de mon coeur [G]Ouvre les yeux de mon coeur Je désire [Am7] Te [F]voir [Fm] Je désire [C]]Te voir [Gsus4] Refrain [C]Tu es saint, Tu es saint [G]Tu es saint, Tu es saint [E] [Am]Tu es saint, Tu es [F]saint Je désire [C]Te voir. ' FROM songs WHERE title = 'OUVRE LES YEUX DE MON CŒUR' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en Bb', '', NULL, 'intro O [Bb]venez adorons-Le O [Dm7]venez [Ebmaj7]ado[Gm]rons-[F]Le O [Cm]venez [Dm7]ado[Eb]rons-[Gm] Le [Bb/F]Christ [F]le Sei[Gm]gneur O [Bb]venez adorons-Le O [Dm7]venez [Ebmaj7]ado[Gm7]rons-[F]Le O [Cm]venez [Bb/Dm7]ado[F7/Eb]rons-[Gm]Le [Bb/F]Christ [F7]le Sei[Bb]gneur Car [Bb]Toi seul en es [Bb]digne, Car [Dm7] Toi seul en es [Gm]di[F]gne Car [Cm7]Toi seul [Bb/Dm]en est [Eb]di[Gm7]gne [Bb/F]Christ [F]le Sei[Bb]gneur Nous [C]Te donnons la gloire Nous [C/Fb]]Te don[F]nons la [Am7]gloi[G]re Nous [Dm7]Te don[Fbm7]nons la [F]gloi[Am7]re [C/G]Christ [G]le Sei[C]gneur Nous [Db]Te louerons à jamais Nous [Fm]Te loue[Gb]rons à [Bbm7]ja[Ab/C]mais Nous [Ebm7]Te loue[Fm7]rons à [Gb]ja[Bb]mais [Cb/A]Christ [Ab]le Sei[Db]gneur Nous [Db]Te louerons à jamais Nous [Fm]Te loue[Gb]rons à [Bbm7]ja[Ab/C]mais Nous [Ebm7]Te loue[Fm7]rons à [Gb]ja[Bb]mais [Cbm]Christ [Ab]le Sei[Db]gneur O [Dbm]venez adorons-Le O [Fm]venez [Gb]ado[Bbm]rons-[Abm]Le O [Ebm]venez [Fm]ado[Gb]rons [Bbm]Le [Cbm]Christ [Ab]le Sei[Db]gneur O [Dbm]venez adorons-Le O [Fm]venez a[Gb]do[Bbm7]rons-[Ab]Le O [Ebm7]venez [Fm]ado[Gb]rons [Bbm]Le [Cbm]Christ [Ab]le Sei[Gb]gneur' FROM songs WHERE title = 'O VENEZ ADOREZ-LE (Peuple Fidèle)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PARDON, SEIGNEUR, PARDON', '', NULL, '' FROM songs WHERE title = 'PARDON, SEIGNEUR, PARDON' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PERE ATTIRE-MOI (O DIEU VIVANT)', '', NULL, '' FROM songs WHERE title = 'PERE ATTIRE-MOI (O DIEU VIVANT)' LIMIT 1;