-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DEVANT TON AUTEL', '', NULL, '' FROM songs WHERE title = 'DEVANT TON AUTEL' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU A UNE ARMEE', '', NULL, '' FROM songs WHERE title = 'DIEU A UNE ARMEE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU EST BON (nous voulons le crier)', '', NULL, '' FROM songs WHERE title = 'DIEU EST BON (nous voulons le crier)' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en D', '', NULL, 'Refrain 1 Dieu est [D]bon, en tout [Bm]temps, Il a [G]mis ce chant de [A]louange en moi. Dieu est [D]bon, en tout [Bm]temps, A tra[G]vers la nuit, sa [A]lumière jaillit. Dieu est [G]bon, Dieu est [A]bon, en tout [D]temps ! [G] [D] Coupet 1 Si tu [A]marches dans les [Bm]ténèbres et que [G]l’ombre t’enva[Bm]hit. Ne crains [F#m]pas, Il te [Bm]guide et Il [G]te protége[A]ra. Il a [Em]promis d’être avec [A]toi, jamais [Em]Il ne t’aban[Bm]donne[A]ra ! Couplet 2 Nous é[A]tions si in[Bm]dignes mais Il [G]est mort pour nous [Bm]tous Il nous [F#m]remplit de son [Bm]Esprit, mainte[G]nant nous décla[A]rons Que son [Em]amour dure à [A]jamais et ses [Em]bontés pour l’é[Bm]terni[A]té ! Pont Même [Bm]si je ne comprends [F#m]pas tous les [Am]plans formés pour [Em]moi. Ma [A#m]vie est dans tes [F]mains et à tra[Em]vers les [D]yeux de la [G]foi je [A]vois' FROM songs WHERE title = 'DIEU EST BON EN TOUT TEMPS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU EST ELEVE', '', NULL, '' FROM songs WHERE title = 'DIEU EST ELEVE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU EST LA', '', NULL, ' Dieu est [Dm]là, [G7] Dieu est [C]là Dieu est [Dm]à pour te bé[G7]nir, Dieu est [Cm7b]là. Dieu est [F]là, pour te b[G7]énir, te con[Em]soler, te gu[A]érir. Si tu [Dm]crois en sa [G7]parole, Dieu est [C]là. Si tu [Dm]crois, [G7]mon a[C]mi, [Am]Cette his[Dm]toire [G7]est pour [Cm7b]toi. C''est pour [F]toi qu''un jour Jésus est appa[Gm7]rût, Et sais-[Em]tu que sans Jésus tu es per[Am]du ? Viens à [Dm]Lui aujourd''[Gm7]hui, toi au[C]ssi.' FROM songs WHERE title = 'DIEU EST LA' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU EST LA SOURCE DE MA JOIE', '', NULL, '' FROM songs WHERE title = 'DIEU EST LA SOURCE DE MA JOIE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU FIDELE (tu ne changes pas)', '', NULL, '' FROM songs WHERE title = 'DIEU FIDELE (tu ne changes pas)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU FIDELE (tu suffis pleinement)', '', NULL, '' FROM songs WHERE title = 'DIEU FIDELE (tu suffis pleinement)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIEU, TU ES GRAND ET DIGNE', '', NULL, '' FROM songs WHERE title = 'DIEU, TU ES GRAND ET DIGNE' LIMIT 1;