-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE TE DONNE TOUT', '', NULL, '' FROM songs WHERE title = 'JE TE DONNE TOUT' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE VEUX CHANTER (UN CHANT D''''AMOUR)', '', NULL, '' FROM songs WHERE title = 'JE VEUX CHANTER (UN CHANT D''AMOUR)' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JOUR DE JOIE', '', NULL, ' intro: [Dm]Jour de joie, jour [Gm]de victoire, [C]Il étend sa [F]main d''en haut [Dm]Me retire des [Gm]grandes eaux, [A7]Il me saisit et me dé[Dm]livre [F]L''Eternel est [Cm7b]mon appui, [Dm]Devant tous mes [A7#]ennemis [Bb]Dieu se lève [C]avec é[F]clat, [Bb]Et Il marche [A7]devant [Dm]moi' FROM songs WHERE title = 'JOUR DE JOIE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'LA DANS LE FEU', '', NULL, '' FROM songs WHERE title = 'LA DANS LE FEU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'LAISSE MOI VOIR TA VIE', '', NULL, '' FROM songs WHERE title = 'LAISSE MOI VOIR TA VIE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc Em', '', NULL, ' Refrain [Em]Là ou est l’Es[Am]prit du Seig[Em]neur [Em]Là ou est l’[Am]Esprit du Seig[Em]neur [Em]C’est la [A]liberté, [Em]c’est la [A]vie [Em]C’est la [A]liberté [B7]de l’Es[Em]prit. Couplet 1 [Em]Il é[Bm]loigne [Em]nos limites [Em]Et trans[Bm]forme nos [Em]sentiments [Em]C’est [Bm]une vraie [Em]dynamite [Em]Bouscu[Bm]lant nos [Em]raison[D]ne[Em]ments Couplet 2 [Em]Nous l’a[Bm]vons vrai[Em]ment reçu [Em]L’Esprit [Bm]promis [Em]par Jésus [Em]Il nous [Bm]libère [Em]par son feu [Em]Pour lou[Bm]er le [Em]nom [D]de [Em]Dieu ' FROM songs WHERE title = 'LA OU EST L’ESPRIT DU SEIGNEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'LE FILS DE DIEU', '', NULL, '' FROM songs WHERE title = 'LE FILS DE DIEU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'LE FLEUVE DE DIEU', '', NULL, '' FROM songs WHERE title = 'LE FLEUVE DE DIEU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'LENT A LA COLERE', '', NULL, '' FROM songs WHERE title = 'LENT A LA COLERE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'LES CIEUX PROCLAMENT', '', NULL, '' FROM songs WHERE title = 'LES CIEUX PROCLAMENT' LIMIT 1;