-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'AUPRES DE DIEU', '', NULL, '' FROM songs WHERE title = 'AUPRES DE DIEU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'AVEC TON ESPRIT', '', NULL, '' FROM songs WHERE title = 'AVEC TON ESPRIT' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'BENIS L''''ETERNEL', '', NULL, 'Couplet 1 Je n''oublie [G]aucun de Tes bienfaits A chaque [D]fois qu''j''y pense mon coeur est rempli De paroles pour Te [C]louer De paroles pour Te [G]louer Refrain O mon [C]âme bénie l''Eter[Em]nel O mon [D]âme bénie l''Eter[C]nel Couplet 2 Quand tout va [Em]mal O mon âme pourquoi t''abats-[Bm]tu? Même au mi[Bm]lieu de la tempête, Il est [D]là (x2) Moi je Le louerai en[C]core Moi je Le louerai en[D]core Refrain 2 O mon [C]âme bénie l''Eter[Em]iel O mon [D]âme bénie l''Eter[C]nel Loba na Yé, nalingaka Yo Yesu Eh' FROM songs WHERE title = 'BENIS L''ETERNEL' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'BENI SOIT LE NOM DU SEIGNEUR', '', NULL, '' FROM songs WHERE title = 'BENI SOIT LE NOM DU SEIGNEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'BENI SOIT LE NOM DU SEIGNEUR (Je demeure)', '', NULL, '' FROM songs WHERE title = 'BENI SOIT LE NOM DU SEIGNEUR (Je demeure)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'BENI SOIT TON NOM', '', NULL, '' FROM songs WHERE title = 'BENI SOIT TON NOM' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'BENISSEZ LE SEIGNEUR', '', NULL, '' FROM songs WHERE title = 'BENISSEZ LE SEIGNEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'BRISER LES CHAINES', '', NULL, '' FROM songs WHERE title = 'BRISER LES CHAINES' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en A', '', NULL, 'Car [D]Dieu est un [A]Dieu puissant Il [E]règne de [F#m]son saint lieu [D]Avec sa[A]gesse, amour Oui [Bm]Dieu est un [C#m]Dieu pui[F#m]ssant Car [D]Dieu est un [A]Dieu puissant Il [E]règne de [F#m]son saint lieu [D]Avec sa[A]gesse, amour Oui [Bm]Dieu est un [C#m]Dieu pui[D]ssant Oui [Bm]Dieu est [C#m]Dieu [E]pui[F#m]ssant' FROM songs WHERE title = 'CAR DIEU EST UN DIEU PUISSANT' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'CAR JE CONNAIS LES PROJETS', '', NULL, '' FROM songs WHERE title = 'CAR JE CONNAIS LES PROJETS' LIMIT 1;