-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Arrangement par défaut', '', NULL, '1 -[D] Digne est l''Agneau[Am] sacrifié,[C] Il est saint, il est [G]saint [D] Un chant nouveau[Am] à celui qui siège[C] sur le trône de [G]grâce Ref :[D] Saint, oui saint, trois fois saint,[Am] Est le Seigneur tout-puissant,[C] Qui est, qui était et [G]qui vient ! [D] Je chante avec la création :[Am] Louange au Roi des rois,[C] Oui, tu es tout pour moi, Et [G]je viens t''adorer 2 -[D] Ceint des couleurs[Am] de arc-en-ciel,[C] Entouré d''éclairs et de [G]bruits de tonnerre, [D] Louange, honneur, Puissance,[Am] force et gloire,[C] sagesse au Roi des [G]rois 3 -[D] Emerveillé,[Am] oui bouleversé,[C] à l’écho de ton [G]nom. [D] Jésus, ton nom est puissance,[Am] Souffle et source d''eau vive.[C] Quel mystère merveil[G]leux !' FROM songs WHERE title = 'DIGNE EST L''AGNEAU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ACCORDS D', '', NULL, '' FROM songs WHERE title = 'DIGNE EST L''AGNEAU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'DIGNE ES-TU', '', NULL, '' FROM songs WHERE title = 'DIGNE ES-TU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ENTENDS MON CŒUR', '', NULL, '' FROM songs WHERE title = 'ENTENDS MON CŒUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'EN TOI JE SAIS QUI JE SUIS', '', NULL, '' FROM songs WHERE title = 'EN TOI JE SAIS QUI JE SUIS' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ESPRIT DE DIEU', '', NULL, '[B][C#][D#m] [B] Oui, nous voulons ê[C#]tre un peuple embras[D#m]é, L’Église que ton c[D#m]œur attend. [B] Viens briser nos ch[C#]aînes, détruis notre org[D#m]ueil, Seigneur, fais-le m[D#m]aintenant. Notre [G#m]Père, plein de bont[D#m]é, nos cœurs [F#]à toi s’aband[C#]onnent. Pour ce [G#m]monde que tu as t[F#/A#]ant aimé, Seigneur, [B]voici nos cour[C#]onnes. Esprit de D[F#]ieu, Esprit du d[D#m]ieu vivant, Souffle du n[B]ord, souffle du s[C#]ud, Souffle de l’[D#m]est, souffle de l’ou[C#/E#]est. Esprit de D[F#]ieu, Esprit du d[D#m]ieu vivant, Souffle des qu[B]atre vents[C#] et descends sur n[F#]ous. [B] Envoie ta puiss[C#]ance, rends-nous les tém[D#m]oins D’un royaume qui s[D#m]e répand. [B] Fais brûler nos cœ[C#]urs au sein des tén[D#m]èbres Comme un phare dans l’[D#m]océan. Notre [G#m]Père, plein de bont[D#m]é, dieu de [F#]tendresse et de gr[C#]âce, Pour ce [G#m]monde que tu as t[F#/A#]ant aimé, fais bril[B]ler sur nous ta f[C#]ace. [B]Que ton règne v[F#/A#]ienne, ta volon[B]té [C#]soit [D#m]faite Sur la t[B]erre comme au c[F#/A#]iel, sur la t[B]erre [C#]comme au c[F#]iel. ' FROM songs WHERE title = 'ESPRIT DE DIEU' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ETERNITE', '', NULL, '' FROM songs WHERE title = 'ETERNITE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'FAISONS MONTER', '', NULL, '' FROM songs WHERE title = 'FAISONS MONTER' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'FEU DU FONDEUR', '', NULL, '' FROM songs WHERE title = 'FEU DU FONDEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'FILS DE DIEU', '', NULL, '' FROM songs WHERE title = 'FILS DE DIEU' LIMIT 1;