-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE CROIS EN JESUS', '', NULL, '' FROM songs WHERE title = 'JE CROIS EN JESUS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE LEVE LES YEUX (Psaume 121)', '', NULL, '' FROM songs WHERE title = 'JE LEVE LES YEUX (Psaume 121)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE LOUE TON NOM ETERNEL', '', NULL, '' FROM songs WHERE title = 'JE LOUE TON NOM ETERNEL' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE M''''ABANDONNE', '', NULL, '[C#m]Je suis là à genoux [E]devant toi, J’abandon[B]ne tout, j’abandon[A]ne tout. Mon [C#m]seul désir alors que [E]tu m’attires, C’est d’être a[B]vec toi, c’est d’être a[A]vec toi. Je m’a[C#m]bandonne. [E] [B] [A] [C#m]Par ta grâce, viens inon[E]der mon âme, J’ai besoin [B]de toi, j’ai besoin [A]de toi. Mes [C#m]bras ouverts, tu entends [E]ma prière, Parle à [B]mon cœur, parle à [A]mon cœur. REFRAIN Je m’a[C#m]bandonne, je m’a[E]bandonne. Je veux te con[F#m7]naître plus, je veux te con[A]naître plus. PONT [A] [E] [B] [F#m7] [C#m] [Bsus] [B] Tel un [A]vent puis[E]sant, souffle [B]maintenant. Dieu, viens ré[F#m7]gner, Dieu, viens ré[C#m]gner en [B]moi. Tel un [A]oura[E]gan, réveil[B]le mon âme. Dieu, viens ré[F#m7]gner, Dieu, viens ré[C#m]gner en [B]moi. ' FROM songs WHERE title = 'JE M''ABANDONNE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE ME DONNE TOUT A TOI', '', NULL, ' G D Em D C Je me donne tout à toi, Je me donne tout à toi, Sers toi de moi (bis) C D G D Am C D 1 - Je suis là, devant toi, Ma vie est entre tes mains Em D Am C D Je désire te voir, Tes désirs se révèlent en moi C D G D Am C D 2 - Prends mon coeur, prends ma vie, Comme un vivant sacrifice Em D Am C D Tous mes plans, tous mes rêves, Je les place entre tes mains G D Em D C Ma vie n''est pas à moi, Mais je suis à toi, Et je me donne, et je me donne à toi' FROM songs WHERE title = 'JE ME DONNE TOUT A TOI' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE N’AI RIEN A CRAINDRE', '', NULL, '' FROM songs WHERE title = 'JE N’AI RIEN A CRAINDRE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'J''''ENTRE DANS TON SANCTUAIRE', '', NULL, '' FROM songs WHERE title = 'J''ENTRE DANS TON SANCTUAIRE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE SUIS LIBRE', '', NULL, '' FROM songs WHERE title = 'JE SUIS LIBRE' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en F', '', NULL, 'F Gm Je suis né pour te louer, [C]Je suis né pour [F]glori[C/E]fier ton [Dm]nom En toutes [Gm]circonstances [C]Apprendre à te [C7]dire merci [F]Je suis né pour [Gm]t''aimer [C]Je suis né pour [F]t''ado[C/E]rer mon [Dm]Dieu Obéir à [Gm]Ta voix [C]Je suis [C7]fais pour [F]Toi ' FROM songs WHERE title = 'JE SUIS NE POUR TE LOUER' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE SUIS VENU TE LOUER', '', NULL, '' FROM songs WHERE title = 'JE SUIS VENU TE LOUER' LIMIT 1;