-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PERE DES LUMIERES', '', NULL, '' FROM songs WHERE title = 'PERE DES LUMIERES' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PERE JE ME DEMANDE (JE CELEBRE TON NOM)', '', NULL, '' FROM songs WHERE title = 'PERE JE ME DEMANDE (JE CELEBRE TON NOM)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PERE (Oui tu es mon père)', '', NULL, '' FROM songs WHERE title = 'PERE (Oui tu es mon père)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PEUPLE DE DIEU, LEVE LES YEUX', '', NULL, '' FROM songs WHERE title = 'PEUPLE DE DIEU, LEVE LES YEUX' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PEUPLES ELEVEZ LES BANNIERES', '', NULL, '' FROM songs WHERE title = 'PEUPLES ELEVEZ LES BANNIERES' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PLONGE-MOI DANS TA RIVIERE', '', NULL, '' FROM songs WHERE title = 'PLONGE-MOI DANS TA RIVIERE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'PLUS ESCLAVE (Je suis enfant de Dieu)', '', NULL, '' FROM songs WHERE title = 'PLUS ESCLAVE (Je suis enfant de Dieu)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'POUR LA DUREE DES TEMPS', '', NULL, '' FROM songs WHERE title = 'POUR LA DUREE DES TEMPS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'POUSSE DES CRIS DE JOIE (L''''ETERNEL A DETOURNE)', '', NULL, '' FROM songs WHERE title = 'POUSSE DES CRIS DE JOIE (L''ETERNEL A DETOURNE)' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en C', '', NULL, ' Refrain [C]Pousse un cri de joie mon âme, [D7]En l''honneur de l''Eternel. [F]Chante avec reconnaissance, [G7]Car il est le Dieu fidèle. [C]Pousse un cri de joie mon âme, [D7]En l''honneur de son grand nom. [F]Réjouis-toi en sa présence, [G7]Car il est fidèle et bon. Couplet 1 [F]C''est lui qui me délivre [C]du poids de mon passé, [D7]C''est lui qui enlève [G7]ma culpabilité. Couplet 2 [F]C''est lui qui me guérit [C]de toutes mes maladies, [D7]C''est lui qui agit 5G7]par grâce dans ma vie. Couplet 3 [F]C''est lui qui me protège, [C]car il est mon Sauveur, [D7]C''est lui qui m''arrache [G7]à toutes mes frayeurs. ' FROM songs WHERE title = 'POUSSE UN CRI DE JOIE' LIMIT 1;