-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VERS TOI SEIGNEUR', '', NULL, '' FROM songs WHERE title = 'VERS TOI SEIGNEUR' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en D', '', NULL, 'REFRAIN Vic[D]toire au [A]Seigneur de la [Bm]vie, Vic[G]toire au [Em]Dieu de l''infi[A]ni ! Vic[D]toire au [G]nom de [A]Jésus-[D]Christ, Vic[D]toire [G]pour le [A]Saint-Es[D]prit ! Le [D]règne est [A]pour le Tout-Puis[Bm]sant, Le [G]règne pour [Em]lui dans tous les [A]temps, Car [D]l''Agneau [G]a ver[A]sé son [D]sang Qui [D]crie vic[G]toire dès [A]mainte[D]nant. Son [D]nom est [A]Parole de [Bm]Dieu, Il [G]juge et [Em]règne dans les [A]cieux ! Il [D]est le [G]Lion [A]de Ju[D]da Qui [D]a tr[G]iomphé [A]du com[D]bat ! Celui qui vit en moi est plus fort Que celui qui est dans le monde ! Alléluia, tu as remporté la victoire Alléluia, tu as tout gagné pour moi' FROM songs WHERE title = 'VICTOIRE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VIENS DANSER AVEC MOI', '', NULL, '' FROM songs WHERE title = 'VIENS DANSER AVEC MOI' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VIENS FEU DE DIEU', '', NULL, '' FROM songs WHERE title = 'VIENS FEU DE DIEU' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VIENS, NE TARDE PLUS : ADORE', '', NULL, '[D]Viens, ne tarde plus, ad[G/D]ore.[D] [A]Viens, ne tarde plus, donn[Em]e ton cœur.[G] [D]Viens tel que tu es, ad[G/D]ore.[D] [A]Viens tel que tu es devan[Em]t ton Dieu.[G] [D]Viens. [G]Un jour, toute langue dira[D] : Tu es Dieu. [G]Un jour, tout genou fléchira[D]. [G]Mais le vrai trésor est pour ceux[Bm] Qui t’ont chois[Em7]i dès aujourd’hui[A].[Asus4][A]' FROM songs WHERE title = 'VIENS, NE TARDE PLUS : ADORE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VIENS SAINT-ESPRIT', '', NULL, '' FROM songs WHERE title = 'VIENS SAINT-ESPRIT' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'VIENS SAINT-ESPRIT VIENS (VOICI NOS COEUR)', '', NULL, '' FROM songs WHERE title = 'VIENS SAINT-ESPRIT VIENS (VOICI NOS COEUR)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'YAHWE', '', NULL, '' FROM songs WHERE title = 'YAHWE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ELEVE-TOI (Nous désirons)', '', NULL, '' FROM songs WHERE title = 'ELEVE-TOI (Nous désirons)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Default Arrangement', '', NULL, '' FROM songs WHERE title = 'Persevere' LIMIT 1;