-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS, AMI DE MON AME', '', NULL, '' FROM songs WHERE title = 'JESUS, AMI DE MON AME' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS A MIS UN CHANT', '', NULL, ' [Dm]Jésus a mis un chant nouveau [Gm]dans nos cœurs, [A]Jésus a mis un chant nouveau [Dm]dans nos cœurs, [D7]Rien ne pourrait nous enlever [Gm]le bonheur [A]Jésus a mis dans nos cœurs un c[Dm]hant [A]nou[Dm]veau [Dm]Jésus, tu as fait de nous des [Gm]frères et sœurs, [A]Jésus, tu as fait de nous des [Dm]frères et sœurs, [D7]Et en nous aimant, nous serons [Gm]dignes de toi. [A]Jésus, tu as fait de nous [Dm]une [A]fa[Dm]mille. [Dm]Jésus, tu nous as do[Gm]nné la vie, [A]Jésus, tu nous as do[Dm]nné la vie, [D7]Comme un fleuve qui déborde de [Gm]notre cœur. [A]Tu veux la répandre tout au[Dm]tour [A]de [Dm]nous. [Dm]Jésus a changé mes larmes [Gm}en danse, [A]Jésus a changé mes larmes [Dm]en danse, [D7]Tu as rempli ma vie d’amour et [Gm]d’espérance. [A]Jésus, c’est pour toi que je dan[Dm]se [A]de [Dm]joie. ' FROM songs WHERE title = 'JESUS A MIS UN CHANT' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS EST ROI', '', NULL, '' FROM songs WHERE title = 'JESUS EST ROI' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS EST SEIGNEUR', '', NULL, '' FROM songs WHERE title = 'JESUS EST SEIGNEUR' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS, NOUS CELEBRONS (TOUS TA VICTOIRE)', '', NULL, '' FROM songs WHERE title = 'JESUS, NOUS CELEBRONS (TOUS TA VICTOIRE)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS, NOUS TE COURONNONS', '', NULL, '' FROM songs WHERE title = 'JESUS, NOUS TE COURONNONS' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'ACC en D', '', NULL, '[D]Jésus, sois le centre Sois ma lu[A7sus4]mière, sois ma [G/B]source, [D]Jésus (bis) [D]Jésus, sois le centre Sois mon es[A7sus4]poir, sois mon [G/B]chant, 5D]Jésus Sois le [A7sus4]feu dans mon [D]cœur, Sois le [A7sus4]vent dans ces [D]voiles Sois la rai[A7sus4]son de ma [D]vie, [A7sus4]Jésus, [G/B]Jésus[D] [D]Jésus, sois ma vision Sois mon che[A7sus4]min, sois mon [G/B]guide, Jé[D]sus ' FROM songs WHERE title = 'JESUS, SOIS LE CENTRE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JESUS, TU ES DIGNE', '', NULL, '' FROM songs WHERE title = 'JESUS, TU ES DIGNE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE T''''AIME DE L''''AMOUR DU SEIGNEUR', '', NULL, '' FROM songs WHERE title = 'JE T''AIME DE L''AMOUR DU SEIGNEUR' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE TE DONNE MON CŒUR', '', NULL, ' G D Em7 C G D Voici mon désir: t''honorer Em7 D Em G F C D Seigneur de tout mon cœur, Je t''adore G D Em C D G Avec tout mon être, je chanterai Em D G F C D Mon amour et ma joie devant toi G D Am Je te donne mon cœur, Je te donne mon âme, C D G Je vis pour toi seigneur D Am Dans tout ce que je fais, Je veux ta volonté C D G Sois le Maître en moi !' FROM songs WHERE title = 'JE TE DONNE MON CŒUR' LIMIT 1;