-- Generated from arrangements_for_d1.json (324 arrangements)
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'GLOIRE À DIEU, CAR IL EST BON', '', NULL, '' FROM songs WHERE title = 'GLOIRE À DIEU, CAR IL EST BON' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en A', '', NULL, '[A]Un jour nouveau se lève, [D]J’élèverai ma voix pour te lou[E]er. [D] [A]Ton nom est sur mes lèvres, j’é[D/A]lèverai ma voix pour te chan[E/A]ter. [D/A] Refrain 1 A toi [E]seul revient [D]la gloire A toi [E]seul revient [D]l’honneur Refrain 2 Quand ton [A]nom est glori[E]fié, Mon âme est rassa[Bm]siée de joie [F#m]Gloire et hon[D]neur te re[A]viennent Quand la [A]terre entière [E]chante, Elle s’écrie envers le [Bm]–Roi des rois [F#m]Gloire et hon[D]neur te re[A]viennent [E]Sei[Bm]gneur mon Roi [F#m]. [D] [Bm]Gloire et hon[D]neur te revien[F#m]nent. [E]. [A]' FROM songs WHERE title = 'GLOIRE ET HONNEUR' LIMIT 1;
INSERT OR REPLACE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'Acc en Em', '', NULL, '[Em]Grandes et mervei[Am]lleuses, [Em]Sont toutes tes [Am]œuvres, [Em]O Sei[Am/F#]gneur, notre [Em]Dieu tout [B7]puissant, [Em]Juste et véri[Am]table [Em]dans toute ta [Am]volon[Em]té, Toi le [Bm7]Roi éter[Em]nel [E] [Am/C]Qui [D]sur la [G/B]terre et [C]dans le ciel, [Am/F#]Est semblable à [B7]toi ? [Am/C]Tu [D]règnes [G/B]sur tout [C]l''univers, [Am/C]Dieu d''Isr[B7]aël ! [Em]Un jour devant [Am]toi, [Em]tout genou flé[Am]chira, [Em]Toute [Am/F#]langue te [Em]béni[B7]ra. [Em]Allélu[Am]ia, [Em]alléluia, [Em]allé[Bm7]luia, a[Em]men ! Laï, [Bm7]laï… [Em] [D] [G] [Am/F#] [Em] [Bm7] [Em]' FROM songs WHERE title = 'GRANDES ET MERVEILLEUSES' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'GUERIS CE PAYS', '', NULL, '' FROM songs WHERE title = 'GUERIS CE PAYS' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'HOSANNA', '', NULL, '' FROM songs WHERE title = 'HOSANNA' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'HOSANNA (au plus haut des cieux)', '', NULL, '' FROM songs WHERE title = 'HOSANNA (au plus haut des cieux)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'HOSANNA (Ouvrons les portes au Roi)', '', NULL, '' FROM songs WHERE title = 'HOSANNA (Ouvrons les portes au Roi)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'HOSANNA (Un chant s''''élève)', '', NULL, '' FROM songs WHERE title = 'HOSANNA (Un chant s''élève)' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'J''''AIME TA PRESENCE', '', NULL, '' FROM songs WHERE title = 'J''AIME TA PRESENCE' LIMIT 1;
INSERT OR IGNORE INTO arrangements (song_id, name, key, tempo, chord_chart) SELECT id, 'JE CHANTE UN ALLELUIA', '', NULL, '' FROM songs WHERE title = 'JE CHANTE UN ALLELUIA' LIMIT 1;