name = "music-service"
main = "worker.ts"
type = "javascript"
compatibility_date = "2026-05-24"

# Fill your Cloudflare account id before deploying
account_id = "c6408608867f869f85cc16572418424a"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "eglise_db"
database_id = "38d955d1-b300-445e-b06e-cfd9b1b953f0" # eglise-db

[env.staging]
name = "music-service-staging"
account_id = "c6408608867f869f85cc16572418424a"
workers_dev = false

[[env.staging.d1_databases]]
binding = "DB"
database_name = "eglise_db"
database_id = "38d955d1-b300-445e-b06e-cfd9b1b953f0"

# Optional: route = "https://music-service.example.com/*"
